<%@ Page Title="Equipment Aging Parameter Sets" Language="C#" MasterPageFile="~/mTSoar.Master" AutoEventWireup="true" CodeBehind="EqAgingParSets.aspx.cs"
    Inherits="TSoar.Equipment.EquipAging.EqAgingParSets" %>
<asp:Content ID="HeaderContent" ContentPlaceHolderID="ContentPlaceHolderHeader" runat="server">
    <asp:Label runat="server" Text="Work with Equipment Aging Parameter Sets" Font-Italic="true" />
</asp:Content>

<asp:Content ID="MainContent" ContentPlaceHolderID="ContentPlaceHolderMain" runat="server">
    <div class="row">
        <div class="col-sm-3">Links:</div>
        <div class="col-sm-3"><a href="EqAgingIntro.aspx">Introduction to / Help for Equipment Aging</a></div>
    </div>
    <div class="row">
        <div class="col-sm-2"><a href="../EqComponents.aspx">Work with Equipment Components</a></div>
        <div class="col-sm-2">Working with Aging Parameter Sets</div>
        <div class="col-sm-2"><a href="OpsCalendars.aspx">Work with Operational Calendars</a></div>
        <div class="col-sm-2"><a href="EqAgingItems.aspx">Work with Equipment Aging Items</a></div>
        <div class="col-sm-2"><a href="EqAgingOperDat.aspx">Work with Operating Data</a></div>
        <div class="col-sm-2"><a href="EqAgingActionItems.aspx">Work with the Equipment Aging Register (List of Action Items)</a></div>
    </div>
    Various control values (parameters) are needed for defining how an aging item behaves. Using parameter sets allows us to save work by reusing them for different aging items.
    <div align="center">
    <asp:Table runat="server" BorderStyle="Solid" BorderWidth="2" class="full-width" BorderColor="Brown" GridLines="Both" CellPadding="5" CellSpacing="5" BackColor="WhiteSmoke">
        <asp:TableHeaderRow BorderStyle="Solid" BorderWidth="2">
            <asp:TableHeaderCell BorderStyle="Solid" BorderWidth="2" HorizontalAlign="Center" CssClass="text-center">
                Aging Parameter Sets
            </asp:TableHeaderCell>
            <asp:TableHeaderCell BorderStyle="Solid" BorderWidth="2" HorizontalAlign="Center" CssClass="text-center">
                &nbsp;&nbsp;&nbsp;
            </asp:TableHeaderCell>
            <asp:TableHeaderCell  BorderStyle="Solid" BorderWidth="2" HorizontalAlign="Center" CssClass="text-center">
                Equipment Aging Parameter Set Details
            </asp:TableHeaderCell>
        </asp:TableHeaderRow>
        <asp:TableRow  BorderStyle="Solid" BorderWidth="2" >
            <asp:TableCell  BorderStyle="Solid" BorderWidth="2">
                <asp:GridView ID="gvEqParsMaster" runat="server" AutoGenerateColumns="false" DataKeyNames="ID"
                    DataSourceID="SqlDataSrc_EqAgParsMaster"
                    OnRowDataBound="gvEqParsMaster_RowDataBound"
                    OnSelectedIndexChanged="gvEqParsMaster_SelectedIndexChanged"
                    GridLines="Both" CssClass="SoarNPGridStyle" Font-Size="Small">
                    <Columns>
                        <asp:TemplateField HeaderStyle-HorizontalAlign="Center" ItemStyle-HorizontalAlign="Center">
                            <HeaderTemplate>
                                <asp:Label ID="lblHIdent" runat="server" Text="Internal Id" Width="60" 
                                    ToolTip="Points to a row in database table EQUIPAGINGPARS with this ID field contents"></asp:Label>
                            </HeaderTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblIIdent" runat="server" Text='<%# Eval("ID") %>' Width="60" ></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>

                        <asp:CommandField ShowSelectButton="true" />
                        <asp:BoundField DataField="sShortDescript" HeaderText="Parameter Set Name" />
                    </Columns>
                </asp:GridView>
            </asp:TableCell>
            <asp:TableCell></asp:TableCell>
            <asp:TableCell  BorderStyle="Solid" BorderWidth="2">
                <asp:DetailsView ID="dvEqPars" runat="server" AutoGenerateRows="false" DataSourceID="SqlDataSrc_EqAgParsDetails"
                    AutoGenerateInsertButton="true" 
                    AutoGenerateEditButton="true" 
                    AutoGenerateDeleteButton="true"
                    CssClass="SoarNPGridStyle"
                    EmptyDataText="No records." 
                    FieldHeaderStyle-HorizontalAlign="Right"
                    FieldHeaderStyle-Width="40%"
                    RowStyle-Width="60%"
                    EditRowStyle-Width="60%"
                    InsertRowStyle-Width="60%"
                    DataKeyNames="ID"
                    OnItemInserted="dvEqPars_ItemInserted" OnItemInserting="dvEqPars_ItemInserting"
                    OnItemUpdated="dvEqPars_ItemUpdated" OnItemUpdating="dvEqPars_ItemUpdating"
                    OnItemDeleting="dvEqPars_ItemDeleting">
                    <Fields>
                        <asp:TemplateField>
                            <HeaderTemplate>Internal ID</HeaderTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblIID" runat="server" Text='<%# Eval("ID") %>'  />
                            </ItemTemplate>
                            <ControlStyle Width="500px" />
                        </asp:TemplateField>

                        <asp:TemplateField>
                            <HeaderTemplate>"<b>sShortDescript</b>": Parameter Set Name</HeaderTemplate>
                            <HeaderStyle CssClass="full-width" />
                            <ItemTemplate><asp:Label ID="lblIDescr" runat="server" Text='<%# Eval("sShortDescript") %>' /></ItemTemplate>
                            <InsertItemTemplate>
                                <asp:TextBox ID="txbIDescr" runat="server" Text="" CssClass="full-width"/>
                            </InsertItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="txbEDescr" runat="server" Text='<%# Bind("sShortDescript") %>' />
                            </EditItemTemplate>
                        </asp:TemplateField>
                                                        
                        <asp:TemplateField>
                            <HeaderTemplate>"<b>sEquipActionType</b>": Equipment Action Type</HeaderTemplate>
                            <ItemTemplate><asp:Label ID="lblIEqAcType" runat="server" Text='<%# Eval("sEquipActionType")  %>' /></ItemTemplate>
                            <InsertItemTemplate>
                                <asp:DropDownList ID="DDLIEqAcType" runat="server" DataSourceID="SqlDataSrc_EqActTypes"
                                        DataTextField="sEquipActionType" DataValueField="ID" />
                            </InsertItemTemplate>
                            <EditItemTemplate>
                                <asp:DropDownList ID="DDLEEqAcType" runat="server" DataSourceID="SqlDataSrc_EqActTypes"
                                        DataTextField="sEquipActionType" DataValueField="ID" SelectedValue='<%# Bind("iEquipActionType")  %>' />
                            </EditItemTemplate>
                        </asp:TemplateField>
                                                        
                        <asp:TemplateField>
                            <HeaderTemplate>
                                "<b>iIntervalElapsed</b>":<asp:Label ID="lblHIntvElapsed" runat="server" Text="Time Interval - Elapsed"
                                    ToolTip="The elapsed time interval between aging events; must be > 0, except use -1 if elapsed time intervals are not used."></asp:Label>
                            </HeaderTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblIIntvElapsed" runat="server" Text='<%# Eval("iIntervalElapsed") %>' ></asp:Label>
                            </ItemTemplate>
                            <InsertItemTemplate>
                                <asp:TextBox ID="txbIIntvElapsed" runat="server" Text="-1" TextMode="SingleLine" ></asp:TextBox>
                                <asp:RegularExpressionValidator runat="server" ControlToValidate="txbIIntvElapsed" ValidationExpression="^(?!\s*$)\s*((-1)?|[1-9]|\d{2,})\s*$"
                                    ErrorMessage="Must be > 0, or -1" Display="Dynamic" ForeColor="Red" BorderStyle="Dotted" BorderColor="Red" BorderWidth="4px"/>
                            </InsertItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="txbEIntvElapsed" runat="server" Text='<%# Bind("iIntervalElapsed") %>' TextMode="SingleLine" ></asp:TextBox>
                                <asp:RegularExpressionValidator runat="server" ControlToValidate="txbEIntvElapsed" ValidationExpression="^(?!\s*$)\s*((-1)?|[1-9]|\d{2,})\s*$"
                                    ErrorMessage="Must be > 0, or -1" Display="Dynamic" ForeColor="Red" BorderStyle="Dotted" BorderColor="Red" BorderWidth="4px"/>
                            </EditItemTemplate>
                        </asp:TemplateField>
                                                        
                        <asp:TemplateField>
                            <HeaderTemplate>"<b>sTimeUnitsElapsed</b>": Elapsed Time Units</HeaderTemplate>
                            <ItemTemplate><asp:Label runat="server" ID="lblIUnitsElapsed" Text='<%# Eval("sTimeUnitsElapsed") %>'/></ItemTemplate>
                            <InsertItemTemplate>
                                <asp:DropDownList ID="DDLIUnitsElapsed" runat="server" >
                                    <asp:ListItem Value="Years" Text="Years" />
                                    <asp:ListItem Value="Quarters" Text="Quarters" />
                                    <asp:ListItem Value="Months" Text="Months" Selected="True" />
                                    <asp:ListItem Value="Weeks" Text="Weeks" />
                                    <asp:ListItem Value="Days" Text="Days" />
                                    <asp:ListItem Value="Hours" Text="Hours" />
                                </asp:DropDownList>
                            </InsertItemTemplate>
                            <EditItemTemplate>
                                <asp:DropDownList ID="DDLEUnitsElapsed" runat="server" SelectedValue='<%# Bind("sTimeUnitsElapsed") %>' >
                                    <asp:ListItem Value="Years" Text="Years" />
                                    <asp:ListItem Value="Quarters" Text="Quarters" />
                                    <asp:ListItem Value="Months" Text="Months" />
                                    <asp:ListItem Value="Weeks" Text="Weeks" />
                                    <asp:ListItem Value="Days" Text="Days" />
                                    <asp:ListItem Value="Hours" Text="Hours" />
                                </asp:DropDownList>
                            </EditItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField>
                            <HeaderTemplate>
                                "<b>cDeadLineMode</b>": <asp:Label ID="lblHDeadLM" runat="server" Text="Deadline Mode"
                                    ToolTip="Deadline Mode: Y, M, W, N, L, C. See Help Pages 5 and 6 for more information; Help Pages are in Introduction to / Help for Equipment Aging (link is above)." />
                            </HeaderTemplate>
                            <ItemTemplate><asp:Label runat="server" ID="lblIDeadLM" Text='<%# Bind("cDeadLineMode") %>' /></ItemTemplate>
                            <InsertItemTemplate>
                                <asp:DropDownList ID="DDLIDeadLM" runat="server" CssClass="full-width">
                                    <asp:ListItem Value="Y" Text=" Y - Yearly on specified month/day" />
                                    <asp:ListItem Value="M" Text=" M - Monthly on specified day of the month" />
                                    <asp:ListItem Value="W" Text=" W - Weekly on specified weekday" />
                                    <asp:ListItem Value="N" Text=" N - Monthly on N-th occurrence of weekday" />
                                    <asp:ListItem Value="L" Text=" L - Last completion date + iIntervalElapsed sTimeUnitsElapsed" />
                                    <asp:ListItem Value="C" Text=" C - Like L, but to end of calendar time interval" Selected="True" />
                                </asp:DropDownList>
                            </InsertItemTemplate>
                            <EditItemTemplate>
                                <asp:DropDownList ID="DDLEDeadLM" runat="server"  CssClass="full-width" SelectedValue='<%# Bind("cDeadLineMode") %>'>
                                    <asp:ListItem Value="Y" Text=" Y - Yearly on specified month/day" />
                                    <asp:ListItem Value="M" Text=" M - Monthly on specified day of the month" />
                                    <asp:ListItem Value="W" Text=" W - Weekly on specified weekday" />
                                    <asp:ListItem Value="N" Text=" N - Monthly on N-th occurrence of weekday" />
                                    <asp:ListItem Value="L" Text=" L - Last completion date + iIntervalElapsed sTimeUnitsElapsed" />
                                    <asp:ListItem Value="C" Text=" C - Like L, but to end of calendar time interval" />
                                </asp:DropDownList>
                            </EditItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField>
                            <HeaderTemplate>
                                "<b>iDeadLineSpt1</b>": <asp:Label ID="lblHDLSpt1" runat="server" Text="Deadline Support Number 1"
                                    ToolTip="iDeadLineSpt1 - Deadline Support 1; see Help Pages 5 and 6; Help Pages are in Introduction to / Help for Equipment Aging (link is above)."></asp:Label>
                            </HeaderTemplate>
                            <ItemTemplate><asp:Label ID="lblIDLSpt1" runat="server" Text='<%# Eval("iDeadLineSpt1") %>' ></asp:Label></ItemTemplate>
                            <InsertItemTemplate>
                                <asp:TextBox ID="txbI_DLSpt1" runat="server" Text="-1" TextMode="SingleLine"></asp:TextBox>
                                <asp:RegularExpressionValidator runat="server" ControlToValidate="txbI_DLSpt1" ValidationExpression="^((-1)|((1[0-2])|([1-9])))$"
                                    ErrorMessage="Must be -1, or between 1 and 12" Display="Dynamic" ForeColor="Red" BorderStyle="Dotted" BorderColor="Red" BorderWidth="4px"/>
                            </InsertItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="txbE_DLSpt1" runat="server" Text='<%# Bind("iDeadLineSpt1") %>' TextMode="SingleLine"></asp:TextBox>
                                <asp:RegularExpressionValidator runat="server" ControlToValidate="txbE_DLSpt1" ValidationExpression="^((-1)|((1[0-2])|([1-9])))$"
                                    ErrorMessage="Must be -1, or between 1 and 12" Display="Dynamic" ForeColor="Red" BorderStyle="Dotted" BorderColor="Red" BorderWidth="4px"/>
                            </EditItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField>
                            <HeaderTemplate>
                                "<b>iDeadLineSpt2</b>": <asp:Label ID="lblHDLSpt2" runat="server" Text="Deadline Support Number 2"
                                    ToolTip="iDeadLineSpt2 - Deadline Support 2; see Help Pages 5 and 6; Help Pages are in Introduction to / Help for Equipment Aging (link is above)."></asp:Label>
                            </HeaderTemplate>
                            <ItemTemplate><asp:Label ID="lblIDLSpt2" runat="server" Text='<%# Eval("iDeadLineSpt2") %>' ></asp:Label></ItemTemplate>
                            <InsertItemTemplate>
                                <asp:TextBox ID="txbI_DLSpt2" runat="server" Text="-1" TextMode="SingleLine"></asp:TextBox>
                                <asp:RegularExpressionValidator runat="server" ControlToValidate="txbI_DLSpt2" ValidationExpression="^((-1)|(\d|([1-2]\d)|3[0-1]))$"
                                    ErrorMessage="Must be -1, or between 0 and 31" Display="Dynamic" ForeColor="Red" BorderStyle="Dotted" BorderColor="Red" BorderWidth="4px"/>
                            </InsertItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="txbE_DLSpt2" runat="server" Text='<%# Bind("iDeadLineSpt2") %>' TextMode="SingleLine"></asp:TextBox>
                                <asp:RegularExpressionValidator runat="server" ControlToValidate="txbE_DLSpt2" ValidationExpression="^((-1)|(\d|([1-2]\d)|3[0-1]))$"
                                    ErrorMessage="Must be -1, or between 0 and 31" Display="Dynamic" ForeColor="Red" BorderStyle="Dotted" BorderColor="Red" BorderWidth="4px"/>
                            </EditItemTemplate>
                        </asp:TemplateField>
                                                        
                        <asp:TemplateField>
                            <HeaderTemplate>
                                "<b>iIntervalOperating</b>":<asp:Label ID="lblHIntvOper" runat="server" Text="Time Interval - Operating"
                                    ToolTip="The operating time interval between aging events; must be > 0, except use -1 if operating/running time intervals are not used."></asp:Label>
                            </HeaderTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblIIntvOper" runat="server" Text='<%# Eval("iIntervalOperating") %>' ></asp:Label>
                            </ItemTemplate>
                            <InsertItemTemplate>
                                <asp:TextBox ID="txbIIntvOper" runat="server" Text="-1" TextMode="SingleLine" ></asp:TextBox>
                                <asp:RegularExpressionValidator runat="server" ControlToValidate="txbIIntvOper" ValidationExpression="^(?!\s*$)\s*((-1)?|[1-9]|\d{2,})\s*$"
                                    ErrorMessage="Must be > 0, or -1" Display="Dynamic" ForeColor="Red" BorderStyle="Dotted" BorderColor="Red" BorderWidth="4px"/>
                            </InsertItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="txbEIntvOper" runat="server" Text='<%# Bind("iIntervalOperating") %>' TextMode="SingleLine" ></asp:TextBox>
                                <asp:RegularExpressionValidator runat="server" ControlToValidate="txbEIntvOper" ValidationExpression="^(?!\s*$)\s*((-1)?|[1-9]|\d{2,})\s*$"
                                    ErrorMessage="Must be > 0, or -1" Display="Dynamic" ForeColor="Red" BorderStyle="Dotted" BorderColor="Red" BorderWidth="4px"/>
                            </EditItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField>
                            <HeaderTemplate>
                                "<b>sTimeUnitsOperating</b>": <asp:Label ID="lblHUnitsOper" runat="server" Text="Time Units - Operating" 
                                    ToolTip="Operating or running time interval units: Years, Quarters, Months, Weeks, Days, or Hours; default is Hours."></asp:Label>
                            </HeaderTemplate>
                            <ItemTemplate><asp:Label runat="server" ID="lblIUnitsOper" Text='<%# Eval("sTimeUnitsOperating") %>'/></ItemTemplate>
                            <InsertItemTemplate>
                                <asp:DropDownList ID="DDLIUnitsOper" runat="server" >
                                    <asp:ListItem Value="Years" Text="Years" />
                                    <asp:ListItem Value="Quarters" Text="Quarters" />
                                    <asp:ListItem Value="Months" Text="Months" />
                                    <asp:ListItem Value="Weeks" Text="Weeks" />
                                    <asp:ListItem Value="Days" Text="Days" />
                                    <asp:ListItem Value="Hours" Text="Hours" Selected="True" />
                                </asp:DropDownList>
                            </InsertItemTemplate>
                            <EditItemTemplate>
                                <asp:DropDownList ID="DDLEUnitsOper" runat="server" SelectedValue='<%# Bind("sTimeUnitsOperating") %>'>
                                    <asp:ListItem Value="Years" Text="Years" />
                                    <asp:ListItem Value="Quarters" Text="Quarters" />
                                    <asp:ListItem Value="Months" Text="Months" />
                                    <asp:ListItem Value="Weeks" Text="Weeks" />
                                    <asp:ListItem Value="Days" Text="Days" />
                                    <asp:ListItem Value="Hours" Text="Hours" />
                                </asp:DropDownList>
                            </EditItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField>
                            <HeaderTemplate>
                                "<b>iIntervalCycles</b>":<asp:Label ID="lblHIntvCycl" runat="server" Text="Time Interval - Number of Cycles"
                                    ToolTip="The number of cycles interval between aging events; must be > 0, except use -1 if number of cycles intervals are not used."></asp:Label>
                            </HeaderTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblIIntvCycl" runat="server" Text='<%# Eval("iIntervalCycles") %>' ></asp:Label>
                            </ItemTemplate>
                            <InsertItemTemplate>
                                <asp:TextBox ID="txbIIntvCycl" runat="server" Text="-1" TextMode="SingleLine" ></asp:TextBox>
                                <asp:RegularExpressionValidator runat="server" ControlToValidate="txbIIntvCycl" ValidationExpression="^(?!\s*$)\s*((-1)?|[1-9]|\d{2,})\s*$"
                                    ErrorMessage="Must be > 0, or -1" Display="Dynamic" ForeColor="Red" BorderStyle="Dotted" BorderColor="Red" BorderWidth="4px"/>
                            </InsertItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="txbEIntvCycl" runat="server" Text='<%# Bind("iIntervalCycles") %>' TextMode="SingleLine" ></asp:TextBox>
                                <asp:RegularExpressionValidator runat="server" ControlToValidate="txbEIntvCycl" ValidationExpression="^(?!\s*$)\s*((-1)?|[1-9]|\d{2,})\s*$"
                                    ErrorMessage="Must be > 0, or -1" Display="Dynamic" ForeColor="Red" BorderStyle="Dotted" BorderColor="Red" BorderWidth="4px"/>
                            </EditItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField>
                            <HeaderTemplate>
                                "<b>iIntervalDistance</b>":<asp:Label ID="lblHIntvDist" runat="server" Text="Time Interval - Distance"
                                    ToolTip="The distance traveled interval between aging events; must be > 0, except use -1 if distance traveled intervals are not used."></asp:Label>
                            </HeaderTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblIIntvDist" runat="server" Text='<%# Eval("iIntervalDistance") %>' ></asp:Label>
                            </ItemTemplate>
                            <InsertItemTemplate>
                                <asp:TextBox ID="txbIIntvDist" runat="server" Text="-1" TextMode="SingleLine" ></asp:TextBox>
                                <asp:RegularExpressionValidator runat="server" ControlToValidate="txbIIntvDist" ValidationExpression="^(?!\s*$)\s*((-1)?|[1-9]|\d{2,})\s*$"
                                    ErrorMessage="Must be > 0, or -1" Display="Dynamic" ForeColor="Red" BorderStyle="Dotted" BorderColor="Red" BorderWidth="4px"/>
                            </InsertItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="txbEIntvDist" runat="server" Text='<%# Bind("iIntervalDistance") %>' TextMode="SingleLine" ></asp:TextBox>
                                <asp:RegularExpressionValidator runat="server" ControlToValidate="txbEIntvDist" ValidationExpression="^(?!\s*$)\s*((-1)?|[1-9]|\d{2,})\s*$"
                                    ErrorMessage="Must be > 0, or -1" Display="Dynamic" ForeColor="Red" BorderStyle="Dotted" BorderColor="Red" BorderWidth="4px"/>
                            </EditItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField>
                            <HeaderTemplate>
                                "<b>sDistanceUnits</b>": <asp:Label ID="lblHUnitsDist" runat="server" Text="Distance Units - Mileage"
                                    ToolTip="Distance units: Miles or Kilometers; default is Miles."></asp:Label>
                            </HeaderTemplate>
                            <ItemTemplate><asp:Label runat="server" ID="lblIUnitsDist" Text='<%# Eval("sDistanceUnits") %>'/></ItemTemplate>
                            <InsertItemTemplate>
                                <asp:DropDownList ID="DDLIUnitsDist" runat="server">
                                    <asp:ListItem Value="Miles" Text="Miles" Selected="True" />
                                    <asp:ListItem Value="Km" Text="Km" />
                                </asp:DropDownList>
                            </InsertItemTemplate>
                            <EditItemTemplate>
                                <asp:DropDownList ID="DDLEUnitsDist" runat="server" SelectedValue='<%# Bind("sDistanceUnits") %>'>
                                    <asp:ListItem Value="Miles" Text="Miles" />
                                    <asp:ListItem Value="Km" Text="Km" />
                                </asp:DropDownList>
                            </EditItemTemplate>
                        </asp:TemplateField>
                                                        
                        <asp:TemplateField>
                            <HeaderTemplate>
                                "<b>sComment</b>": <asp:Label ID="lblHComment" runat="server" Text="Comments/Notes"></asp:Label>
                            </HeaderTemplate>
                            <ItemTemplate><asp:Label runat="server" ID="lblIComment" Text='<%# Eval("sComment") %>' /></ItemTemplate>
                            <InsertItemTemplate>
                                <asp:TextBox ID="txbIComment" runat="server" Text="" Width="400" />
                            </InsertItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="txbEComment" runat="server" Text='<%# Bind("sComment") %>' Width="400" />
                            </EditItemTemplate>
                        </asp:TemplateField>

                    </Fields>
                </asp:DetailsView>
            </asp:TableCell>
        </asp:TableRow>
    </asp:Table>
    </div>

    <asp:SqlDataSource ID="SqlDataSrc_EqAgParsMaster" runat="server" ConnectionString="<%$ ConnectionStrings:SqlConn %>"
        SelectCommand="SELECT ID, sShortDescript FROM EQUIPAGINGPARS ORDER BY sShortDescript" >
    </asp:SqlDataSource>

    <asp:SqlDataSource ID="SqlDataSrc_EqActTypes" runat="server" ConnectionString="<%$ ConnectionStrings:SqlConn %>"
        SelectCommand="SELECT ID, sEquipActionType FROM EQUIPACTIONTYPES ORDER BY sEquipActionType">
    </asp:SqlDataSource>

    <asp:SqlDataSource ID="SqlDataSrc_EqAgParsDetails" runat="server" ConnectionString="<%$ ConnectionStrings:SqlConn %>" 
        SelectCommand="SELECT P.*, T.sEquipActionType
                       FROM EQUIPAGINGPARS P
                           INNER JOIN EQUIPACTIONTYPES T ON P.iEquipActionType = T.ID
                       WHERE (P.ID = @EqAgParsID)"
        DeleteCommand="DELETE FROM EQUIPAGINGPARS WHERE (ID = @EqAgParsID)"
        InsertCommand="INSERT INTO EQUIPAGINGPARS (sShortDescript, iEquipActionType, iIntervalElapsed, sTimeUnitsElapsed, cDeadLineMode, iDeadLineSpt1, iDeadLineSpt2,
            iIntervalOperating, sTimeUnitsOperating, iIntervalDistance, sDistanceUnits, iIntervalCycles, sComment)
                       VALUES (@sShortDescript, @iEquipActionType, @iIntervalElapsed, @sTimeUnitsElapsed, @cDeadLineMode, @iDeadLineSpt1, @iDeadLineSpt2,
            @iIntervalOperating, @sTimeUnitsOperating, @iIntervalDistance, @sDistanceUnits, @iIntervalCycles, @sComment)"
        UpdateCommand="UPDATE EQUIPAGINGPARS SET sShortDescript=@sShortDescript, iEquipActionType=@iEquipActionType, iIntervalElapsed=@iIntervalElapsed,
            sTimeUnitsElapsed=@sTimeUnitsElapsed, cDeadLineMode=@cDeadLineMode, iDeadLineSpt1=@iDeadLineSpt1, iDeadLineSpt2=@iDeadLineSpt2,
            iIntervalOperating=@iIntervalOperating, sTimeUnitsOperating=@sTimeUnitsOperating, iIntervalDistance=@iIntervalDistance, sDistanceUnits=@sDistanceUnits,
            iIntervalCycles=@iIntervalCycles, sComment=@sComment WHERE (ID = @EqAgParsID)">
        <SelectParameters>
            <asp:ControlParameter ControlID="gvEqParsMaster" Name="EqAgParsID" PropertyName="SelectedValue" Type="Int32" />
        </SelectParameters>
        <DeleteParameters>
            <asp:ControlParameter ControlID="dvEqPars$lblIID" Name="EqAgParsID" PropertyName="Text" Type="Int32" />
        </DeleteParameters>
        <InsertParameters>
            <asp:ControlParameter ControlID="dvEqPars$txbIDescr" Name="sShortDescript" PropertyName="Text" Type="String" ConvertEmptyStringToNull="true" />
            <asp:ControlParameter ControlID="dvEqPars$DDLIEqAcType" Name="iEquipActionType" PropertyName="SelectedValue" Type="Int32" />
            <asp:ControlParameter ControlID="dvEqPars$txbIIntvElapsed" Name="iIntervalElapsed" PropertyName="Text" Type="Int32" />
            <asp:ControlParameter ControlID="dvEqPars$DDLIUnitsElapsed" Name="sTimeUnitsElapsed" PropertyName="SelectedValue" Type="String" ConvertEmptyStringToNull="true" />
            <asp:ControlParameter ControlID="dvEqPars$DDLIDeadLM" Name="cDeadLineMode" PropertyName="SelectedValue" Type="Char" />
            <asp:ControlParameter ControlID="dvEqPars$txbI_DLSpt1" Name="iDeadLineSpt1" PropertyName="Text" Type="Int32" />
            <asp:ControlParameter ControlID="dvEqPars$txbI_DLSpt2" Name="iDeadLineSpt2" PropertyName="Text" Type="Int32" />
            <asp:ControlParameter ControlID="dvEqPars$txbIIntvOper" Name="iIntervalOperating" PropertyName="Text" Type="Int32" />
            <asp:ControlParameter ControlID="dvEqPars$DDLIUnitsOper" Name="sTimeUnitsOperating" PropertyName="SelectedValue" Type="String" ConvertEmptyStringToNull="true" />
            <asp:ControlParameter ControlID="dvEqPars$txbIIntvDist" Name="iIntervalDistance" PropertyName="Text" Type="Int32" />
            <asp:ControlParameter ControlID="dvEqPars$DDLIUnitsDist" Name="sDistanceUnits" PropertyName="SelectedValue" Type="String" ConvertEmptyStringToNull="true" />
            <asp:ControlParameter ControlID="dvEqPars$txbIIntvCycl" Name="iIntervalCycles" PropertyName="Text" Type="Int32" />
            <asp:ControlParameter ControlID="dvEqPars$txbIComment" Name="sComment" PropertyName="Text" Type="String" ConvertEmptyStringToNull="true" />
        </InsertParameters>
        <UpdateParameters>
            <asp:ControlParameter ControlID="dvEqPars$lblIID" Name="EqAgParsID" PropertyName="Text" Type="Int32" />
            <asp:ControlParameter ControlID="dvEqPars$txbEDescr" Name="sShortDescript" PropertyName="Text" Type="String" ConvertEmptyStringToNull="true" />
            <asp:ControlParameter ControlID="dvEqPars$DDLEEqAcType" Name="iEquipActionType" PropertyName="SelectedValue" Type="Int32" />
            <asp:ControlParameter ControlID="dvEqPars$txbEIntvElapsed" Name="iIntervalElapsed" PropertyName="Text" Type="Int32" />
            <asp:ControlParameter ControlID="dvEqPars$DDLEUnitsElapsed" Name="sTimeUnitsElapsed" PropertyName="SelectedValue" Type="String" ConvertEmptyStringToNull="true" />
            <asp:ControlParameter ControlID="dvEqPars$DDLEDeadLM" Name="cDeadLineMode" PropertyName="SelectedValue" Type="Char" />
            <asp:ControlParameter ControlID="dvEqPars$txbE_DLSpt1" Name="iDeadLineSpt1" PropertyName="Text" Type="Int32" />
            <asp:ControlParameter ControlID="dvEqPars$txbE_DLSpt2" Name="iDeadLineSpt2" PropertyName="Text" Type="Int32" />
            <asp:ControlParameter ControlID="dvEqPars$txbEIntvOper" Name="iIntervalOperating" PropertyName="Text" Type="Int32" />
            <asp:ControlParameter ControlID="dvEqPars$DDLEUnitsOper" Name="sTimeUnitsOperating" PropertyName="SelectedValue" Type="String" ConvertEmptyStringToNull="true" />
            <asp:ControlParameter ControlID="dvEqPars$txbEIntvDist" Name="iIntervalDistance" PropertyName="Text" Type="Int32" />
            <asp:ControlParameter ControlID="dvEqPars$DDLEUnitsDist" Name="sDistanceUnits" PropertyName="SelectedValue" Type="String" ConvertEmptyStringToNull="true" />
            <asp:ControlParameter ControlID="dvEqPars$txbEIntvCycl" Name="iIntervalCycles" PropertyName="Text" Type="Int32" />
            <asp:ControlParameter ControlID="dvEqPars$txbEComment" Name="sComment" PropertyName="Text" Type="String" ConvertEmptyStringToNull="true" />
        </UpdateParameters>
    </asp:SqlDataSource>

    <div>
        <%-- ModalPopupExtender, popping up MPE_Panel and dynamically populating lblPopupText --%>
        <asp:LinkButton ID="Target" runat="server" Text="T" CssClass="displayNone" />
        <ajaxToolkit:ModalPopupExtender ID="ModalPopExt" runat="server"
            TargetControlID="Target" PopupControlID="MPE_Panel"
            BackgroundCssClass="background"
             />
        <asp:Panel ID="MPE_Panel" runat="server" CssClass="popup" style="display:none;" HorizontalAlign="Center">
            <asp:Label ID="lblPopupText" runat="server" BackColor="#eeb5a2" Font-Bold="true" />
            <br /><br />
            <p> <asp:Button ID="OkButton" runat="server" Text="OK" OnClick="Button_Click" />&nbsp;&nbsp;
                <asp:Button ID="CancelButton" runat="server" Text="Cancel" OnClick="Button_Click" />&nbsp;&nbsp;
                <asp:Button ID="NoButton" runat="server" Text="No" OnClick="Button_Click" />&nbsp;&nbsp;
                <asp:Button ID="YesButton" runat="server" Text="Yes" OnClick="Button_Click"/></p>
        </asp:Panel>
    </div>

</asp:Content>

<asp:Content ID="FooterContent" ContentPlaceHolderID="ContentPlaceHolderFooter" runat="server">
    <%: Title %>
</asp:Content>
