<?xml version="1.0" encoding="utf-8"?><Database Name="SoarDB" Class="ManageSettingsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=C1325433-H\SQLSERVER2014A;Initial Catalog=SoarDB;Persist Security Info=False;User ID=SoarNP" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SoarDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.aspnet_Roles" Member="aspnet_Roles">
    <Type Name="aspnet_Role">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredRoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="aspnet_Role_SETTINGSROLESBRIDGE" Member="SETTINGSROLESBRIDGEs" ThisKey="RoleId" OtherKey="uiRole" Type="SETTINGSROLESBRIDGE" />
    </Type>
  </Table>
  <Table Name="dbo.SETTINGS" Member="SETTINGs">
    <Type Name="SETTING">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sSettingName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sExplanation" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sSettingValue" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sInTable" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sComments" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="bUserSelectable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="SETTING_SETTINGSROLESBRIDGE" Member="SETTINGSROLESBRIDGEs" ThisKey="ID" OtherKey="iSetting" Type="SETTINGSROLESBRIDGE" />
    </Type>
  </Table>
  <Table Name="dbo.SETTINGSROLESBRIDGE" Member="SETTINGSROLESBRIDGEs">
    <Type Name="SETTINGSROLESBRIDGE">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PiTRecordEntered" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="iRecordEnteredBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="iSetting" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="uiRole" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="sComments" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="aspnet_Role_SETTINGSROLESBRIDGE" Member="aspnet_Role" ThisKey="uiRole" OtherKey="RoleId" Type="aspnet_Role" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="SETTING_SETTINGSROLESBRIDGE" Member="SETTING" ThisKey="iSetting" OtherKey="ID" Type="SETTING" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_ManageSettings" Method="sp_ManageSettings">
    <Parameter Name="sUser" Type="System.String" DbType="NVarChar(256)" />
    <ElementType Name="sp_ManageSettingsResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sSettingName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sExplanation" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sSettingValue" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="cSettingType" Type="System.Char" DbType="NChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="sSelectStmnt" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="dLow" Type="System.Decimal" DbType="Decimal(12,4)" CanBeNull="true" />
      <Column Name="dHigh" Type="System.Decimal" DbType="Decimal(12,4)" CanBeNull="true" />
      <Column Name="sDataValueField" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sDataTextField" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>