SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF (OBJECT_ID('sp_EquipRolesTypes') IS NOT NULL) DROP PROCEDURE sp_EquipRolesTypes
GO
CREATE PROCEDURE sp_EquipRolesTypes
AS
BEGIN
SELECT	EQUIPROLESTYPES.ID,
		EQUIPMENTROLES.ID AS iRole,
		CONVERT(nvarchar(12), EQUIPMENTROLES.ID) + N' - ' + EQUIPMENTROLES.sEquipmentRole AS sRole,
		EQUIPTYPES.ID AS iType,
		CONVERT(nvarchar(12), EQUIPTYPES.ID) + N' - ' + EQUIPTYPES.sEquipmentType AS sType,
		EQUIPROLESTYPES.sComments
	FROM EQUIPMENTROLES
		INNER JOIN EQUIPROLESTYPES ON EQUIPMENTROLES.ID = EQUIPROLESTYPES.iEquipRole
		INNER JOIN EQUIPTYPES ON EQUIPROLESTYPES.iEquipType = EQUIPTYPES.ID
END