SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF (OBJECT_ID('sp_StatsRptByGlider') IS NOT NULL) DROP PROCEDURE sp_StatsRptByGlider
GO
-- Generate report on glider flying statistics by Glider Year
CREATE PROCEDURE sp_StatsRptByGlider
AS
BEGIN
	SELECT EQUIPMENT.sShortEquipName + ' - ' + EQUIPMENT.sOwner AS [Glider - Owner], YEAR(OPERATIONS.DBegin) AS Year,
		ROUND(SUM(DATEDIFF(mi, OPERATIONS.DBegin, OPERATIONS.DEnd)) / 60.0, 2) AS [Flight Hours], MAX(' ') AS SubGlider, MAX(' ') AS Total
		FROM EQUIPMENT
			INNER JOIN OPDETAILS ON EQUIPMENT.ID = OPDETAILS.iEquip
			INNER JOIN OPERATIONS ON OPDETAILS.iOperation = OPERATIONS.ID
			INNER JOIN EQUIPMENTROLES ON OPDETAILS.iEquipmentRole = EQUIPMENTROLES.ID
		WHERE (EQUIPMENTROLES.sEquipmentRole = N'Glider') AND (OPERATIONS.DBegin >= CONVERT(DATETIME, '2017-01-01 00:00:00', 102))
		GROUP BY EQUIPMENT.sShortEquipName + ' - ' + EQUIPMENT.sOwner, YEAR(OPERATIONS.DBegin) WITH ROLLUP
END