SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
USE SoarDB
GO
IF (OBJECT_ID('TNPF_Aviators2bCharged') IS NOT NULL) DROP FUNCTION TNPF_Aviators2bCharged
GO
CREATE FUNCTION TNPF_Aviators2bCharged (@iOpID int)
RETURNS int WITH RETURNS NULL ON NULL INPUT
AS
BEGIN
	DECLARE @iNumAv int
	SELECT @iNumAv = COUNT(*)
		FROM AVIATORS A
             INNER JOIN OPDETAILS D ON A.iOpDetail = D.ID
             INNER JOIN OPERATIONS O ON D.iOperation = O.ID
		WHERE (O.ID = @iOpID) AND (A.dPercentCharge > 0)
	RETURN @iNumAv
END
GO